### PR TITLE
chore: move specific deps to package

### PR DESCRIPTION
**Pull request by alexanderczigler**
I noticed that the published pubsub package did not include its required dependencies. I have moved these to the pubsub package.json so they should be published along with the package from now on.

### CODE REVIEW

**Comment by alexanderczigler** [comment]
Rare houses roll 🤭

**Comment by believer** [comment]
If we want to install a dependency in a specific package, we should use e.g. `yarn workspace @sebspark/typed-router add is-even` from now on.

PS. I'm thinking of adding workspace installs to [supreme](https://github.com/opendevtools/supreme) to reduce the amount of typing needed.

**Comment by alexanderczigler** [comment]
@believer I re-added the dependencies using that method.

The test and lint runs are broken right now but this change only affects dependencies so it should be safe to merge.

**Comment by believer** [comment]
@alexanderczigler Yeah, but why are they broken? 🤔

**Comment by alexanderczigler** [comment]
@believer very good question 🤔 
It might be a problem introduced in `1.10.6` according to https://github.com/vercel/turbo/discussions/5290

**Comment by alexanderczigler** [comment]
Oh! 😑 

A `package-lock.json` has been added here. I thought it was just modified so I did not pay attention to it. That files seems to cause the problem.

**Comment by believer** [comment]
Haha I didn't even notice that. Nice catch!

**Pull request merged**
